[orover]
python_exec = python3
heartbeat_interval = 20
loglevel = DEBUG  
logfile = orover.log
logdir = logs
max_logfiles = 10
logformat = %(asctime)s %(name)-8s %(levelname)-9s %(guid)s %(message)s
logdatefmt = %Y-%m-%d %H:%M:%S

[app]
static_folder = static
template_folder = template
debug = True
host=0.0.0.0
port=5000
secret_key = 4HgUd6e27cMEg8rx3vbF

[scripts]
logger   = logserver.py
eventbus = eventbus.py
boss     = boss.py
;pwrctrl  = powercontrol.py
hcsr04 = hcsr04.py
ugv    = ugv.py
;webrover = app.py

[eventbus]
client_pub_socket = tcp://localhost:5556
client_sub_socket = tcp://localhost:5555
bus_xsub_socket = tcp://localhost:5556
bus_xpub_socket = tcp://*:5555
capture_message_ids = True

[serial]
port = /dev/serial0
baudrate = 115200

[powercontrol]
pin = 4
sleep_time = 2.0

[hcsr04]
sensor1 = sensor_ultrasonic_front, 25, 5 
min_obj_distance = 20.0
polling_interval = 0.5
echo_timeout = 0.04
speed_of_sound = 34300.0

[lister]
ignore_heartbeat = True
